### ISSUE TITLE
Coyote Badger Launch Error - Windows Desktop

### ISSUE THREAD

**Issue by tfryed** [alexsands/coyote-badger#10]
I received the following error after trying to run the initiation code on my Windows Dekstop (MS Windows 10 Home - x64 - Intel i7) 

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
docker: Error response from daemon: create %cd%/projects: "%cd%/projects" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

I was able to get Coyote Badger to run on port 5000 by removing the ":" from the string %cd%/_projects:/opt/coyotebadger/_projects
The initiation code that I tried to use here was - 

docker build . -t coyotebadger:latest
docker run -it --rm --name coyotebadger --ipc="host" --shm-size="1gb" --memory="2g" --cpus="2" -v %cd%/_projects/opt/coyotebadger/_projects -p 5000:5000 coyotebadger:latest

However, this made it impossible for Coyote Badger to properly run when I opened http://localhost:5000/ in Mozilla Firefox. 
It looks like deleting the ":" made it impossible to recognize the directory (this should have been unsurprising, but I was just fooling around a bit to see if I could get this to work). 

Here is the error that I received. Let me know if you need me to get any additional information on this issue. While this is lower priority for me than getting Coyote Badger working on Apple M1 chips, I'd also like to be able to run Coyote Badger on my windows Desktop.

FileNotFoundError: [Errno 2] No such file or directory: '/opt/coyotebadger/_projects'
Traceback (most recent call last)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app

    response = self.handle_exception(e)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/opt/coyotebadger/coyote_badger/app.py", line 56, in index

    projects = Project.get_projects()

    File "/opt/coyotebadger/coyote_badger/project.py", line 82, in get_projects

    for item in os.listdir(PROJECTS_FOLDER):

    FileNotFoundError: [Errno 2] No such file or directory: '/opt/coyotebadger/_projects'

**Comment by alexsands** [comment]
Oh awesome! I also don't have a Windows computer so have never been able to test it on there easily. This looks like it should be a pretty simple fix though. I'll get M1 stuff working first and then—if you wouldn't mind doing a Zoom for like 30 min at some point in the next few weeks—I'll make sure it works on your PC as well.

**Comment by alexsands** [comment]
Should be fixed in v2.1.1.
